### ISSUE TITLE
How to write config.yaml for custom datasets

### ISSUE THREAD

**Issue by loliq** [ChenWu98/cycle-diffusion#31]
Thanks for sharing your work.

I want to train my customed unpaired image to image tasks. And I found[ this tutorial](https://github.com/ChenWu98/cycle-diffusion/issues/9#issuecomment-1317875364) . But I have a question about how to write customed yaml like `afhq.yaml`:
```
data:
    dataset: "AFHQ"
    category: "dog"
    image_size: 256
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 0

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
```
Is it automatically generated or can I customize it?

Looking for your replying. Thanks.
